# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: save.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsave.proto\x12\x02\x61i\";\n\tAgeGender\x12\x11\n\tredis_key\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06gender\x18\x03 \x01(\t\".\n\tLandmarks\x12\x11\n\tredis_key\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x03(\x02\"%\n\x11\x41geGenderResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\"%\n\x11LandmarksResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32t\n\x04save\x12\x35\n\rSaveAgeGender\x12\r.ai.AgeGender\x1a\x15.ai.AgeGenderResponse\x12\x35\n\rSaveLandmarks\x12\r.ai.Landmarks\x1a\x15.ai.LandmarksResponseb\x06proto3')



_AGEGENDER = DESCRIPTOR.message_types_by_name['AgeGender']
_LANDMARKS = DESCRIPTOR.message_types_by_name['Landmarks']
_AGEGENDERRESPONSE = DESCRIPTOR.message_types_by_name['AgeGenderResponse']
_LANDMARKSRESPONSE = DESCRIPTOR.message_types_by_name['LandmarksResponse']
AgeGender = _reflection.GeneratedProtocolMessageType('AgeGender', (_message.Message,), {
  'DESCRIPTOR' : _AGEGENDER,
  '__module__' : 'save_pb2'
  # @@protoc_insertion_point(class_scope:ai.AgeGender)
  })
_sym_db.RegisterMessage(AgeGender)

Landmarks = _reflection.GeneratedProtocolMessageType('Landmarks', (_message.Message,), {
  'DESCRIPTOR' : _LANDMARKS,
  '__module__' : 'save_pb2'
  # @@protoc_insertion_point(class_scope:ai.Landmarks)
  })
_sym_db.RegisterMessage(Landmarks)

AgeGenderResponse = _reflection.GeneratedProtocolMessageType('AgeGenderResponse', (_message.Message,), {
  'DESCRIPTOR' : _AGEGENDERRESPONSE,
  '__module__' : 'save_pb2'
  # @@protoc_insertion_point(class_scope:ai.AgeGenderResponse)
  })
_sym_db.RegisterMessage(AgeGenderResponse)

LandmarksResponse = _reflection.GeneratedProtocolMessageType('LandmarksResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANDMARKSRESPONSE,
  '__module__' : 'save_pb2'
  # @@protoc_insertion_point(class_scope:ai.LandmarksResponse)
  })
_sym_db.RegisterMessage(LandmarksResponse)

_SAVE = DESCRIPTOR.services_by_name['save']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGEGENDER._serialized_start=18
  _AGEGENDER._serialized_end=77
  _LANDMARKS._serialized_start=79
  _LANDMARKS._serialized_end=125
  _AGEGENDERRESPONSE._serialized_start=127
  _AGEGENDERRESPONSE._serialized_end=164
  _LANDMARKSRESPONSE._serialized_start=166
  _LANDMARKSRESPONSE._serialized_end=203
  _SAVE._serialized_start=205
  _SAVE._serialized_end=321
# @@protoc_insertion_point(module_scope)
