# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import save_pb2 as save__pb2


class saveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveAgeGender = channel.unary_unary(
                '/ai.save/SaveAgeGender',
                request_serializer=save__pb2.AgeGender.SerializeToString,
                response_deserializer=save__pb2.AgeGenderResponse.FromString,
                )
        self.SaveLandmarks = channel.unary_unary(
                '/ai.save/SaveLandmarks',
                request_serializer=save__pb2.Landmarks.SerializeToString,
                response_deserializer=save__pb2.LandmarksResponse.FromString,
                )


class saveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveAgeGender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveLandmarks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_saveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveAgeGender': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveAgeGender,
                    request_deserializer=save__pb2.AgeGender.FromString,
                    response_serializer=save__pb2.AgeGenderResponse.SerializeToString,
            ),
            'SaveLandmarks': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveLandmarks,
                    request_deserializer=save__pb2.Landmarks.FromString,
                    response_serializer=save__pb2.LandmarksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.save', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class save(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveAgeGender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.save/SaveAgeGender',
            save__pb2.AgeGender.SerializeToString,
            save__pb2.AgeGenderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveLandmarks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.save/SaveLandmarks',
            save__pb2.Landmarks.SerializeToString,
            save__pb2.LandmarksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
